name: CI/CD

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./day-10   
jobs:
  build-docker:
    name: "Build Docker Container"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: create env file
        env:
          PORT: ${{ secrets.PORT }} 
          SECRET_JWT: ${{ secrets.SECRET_JWT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          touch .env
          echo PORT=$PORT >> .env
          echo DB_USER=$DB_USER >> .env
          echo DB_PASS=$DB_PASS >> .env
          echo DB_HOST=$DB_HOST >> .env
          echo DB_PORT=$DB_PORT >> .env
          echo DB_NAME=$DB_NAME >> .env
          echo SECRET_JWT=$SECRET_JWT >> .env

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} 
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: build docker container
        run: docker build -t fjasper13/alterra-agmc-day-10:latest .
      
      - name: push docker container
        run: docker push fjasper13/alterra-agmc-day-10:latest

  deploy:
    name: Deploy to Heroku on main branch push
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web 
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web 